apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: agile-demo-staging
  labels:
    app: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: jinnerbichler/agile-demo-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  ports:
    - port: 8000
      targetPort: 80
  selector:
    app: frontend-service